apiVersion: networking.istio.io/v1
kind: Gateway
metadata:
  name: {{ .Release.Name }}-istio-gateway
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: {{ .Values.service.port }}
      name: http2
      protocol: HTTP
    hosts:
    - "*"
