apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Release.Name }}-istio-route
spec:
  hosts:
  - "*"
  gateways:
  - ws-istio-gateway
  http:
  - route:
    - destination:
        host: {{ .Release.Name }}-svc
        port:
          number: {{ .Values.service.port }}
      headers:
        response:
          set:
            X-Api: "true"
    match:
    - uri:
        prefix: /api
    rewrite:
      uri: ""
