---
apiVersion: v1
kind: Service
metadata:
  name: product-svc
  labels:
    app: {{ .Release.Name }}svc
    release: {{ .Release.Name }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.apiPort }}
      targetPort: {{ .Values.service.apiPort }}
      protocol: TCP
      name: http
  selector:
    app: {{ .Release.Name }}api
    release: {{ .Release.Name }}
---
apiVersion: v1
kind: Service
metadata:
  name: productdb-svc
  labels:
    app: {{ .Release.Name }}dbsvc
    release: {{ .Release.Name }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.dbPort }}
      targetPort: {{ .Values.service.dbPort }}
      protocol: TCP
      name: mysql
  selector:
    app: {{ .Release.Name }}db
    release: {{ .Release.Name }}
