versionTag: v1.1

api:
  replicaCount: 1
  image:
    repository: docker.io/danijels/cg-vat-api
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 8080

database:
  dbPort: 3306
  image:
    repository: mysql
    tag: "8.0"
  replicas: 1
  rootPassword: rootpassword
  databaseName: categories

resources:
  limits:
    cpu: 100m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 256Mi
