versionTag: v0.5

api:
  replicaCount: 1
  image:
    repository: docker.io/danijels/cg-vat-api
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 8080

database:
  dbPort: 3306
  image:
    repository: mysql
    tag: "8.0"
  replicas: 1
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi
  rootPassword: password
  databaseName: categories
