apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Release.Name }}-istio-route
spec:
  hosts:
  - "*"
  gateways:
  - {{ .Release.Name }}-istio-gateway
  http:
  - route:
    - destination:
        host: {{ .Release.Name }}-svc
        port:
          number: {{ .Values.service.port }}
      headers:
        response:
          set:
            X-Version: "{{ .Release.Name }}:{{ .Values.versionTag }}"
    match:
    - uri:
        prefix: /ui/{{ .Release.Namespace }}/
    rewrite:
      uri: "/"

