apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-{{ .Values.database.initScriptConfigMap }}
data:
  init.sql: |
    CREATE TABLE IF NOT EXISTS distributors (
        id INT AUTO_INCREMENT PRIMARY KEY,
        name VARCHAR(255) NOT NULL,
        address VARCHAR(255) NOT NULL,
        percentage_fee DECIMAL(5,2) NOT NULL,
        capacity DECIMAL(5,2) NOT NULL,
        shipping INT NOT NULL
    );

    insert into distributors
    (id, name, address, percentage_fee, capacity, shipping) 
    VALUES
        (100, "ASKO", "Kalbakken", 15, 45, 5),
        (101, "Posten", "Jerbanetorget", 10, 75, 6),
        (102, "DHL", "Oslo", 25, 86, 2),
        (103, "HeltHjem", "Schibsted", 10, 90, 2);

    CREATE TABLE IF NOT EXISTS distr_category (
        distr_id INT NOT NULL,
        cat VARCHAR(4) NOT NULL,
        FOREIGN KEY (distr_id) REFERENCES distributors(id)
    );

    insert into distr_category
    (distr_id, cat) 
    VALUES
        (100, "cosm"),
        (100, "food"),
        (101, "cosm"),
        (101, "toys"),
        (101, "book"),
        (102, "food"),
        (102, "book"),
        (103, "book");
