apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-{{ .Values.database.initScriptConfigMap }}
data:
  init.sql: |
    CREATE TABLE IF NOT EXISTS distributors (
        id INT AUTO_INCREMENT PRIMARY KEY,
        name VARCHAR(255) NOT NULL,
        address VARCHAR(255) NOT NULL,
        percentage_fee DECIMAL(5,2) NOT NULL,
        capacity DECIMAL(5,2) NOT NULL,
        shipping INT NOT NULL
    );

    insert into distributors
    (name, address, percentage_fee, capacity, shipping) 
    VALUES
        ("ASKO", "Kalbakken", 15, 45, 5),
        ("Posten", "Jerbanetorget", 10, 75, 6),
        ("DHL", "Oslo", 25, 86, 2),
        ("HeltHjem", "Schibsted", 10, 90, 2)

    CREATE TABLE IF NOT EXISTS distr_category (
        distr_id INT,
        cat VARCHAR(4),
        FOREIGN KEY (distr_id) REFERENCES distributors(id)
    );

