apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-api
  labels:
    app: {{ .Release.Name }}api
    release: {{ .Release.Name }}
    version: {{ .Values.versionTag }}
spec:
  {{- if not .Values.api.autoscaling.enabled }}
  replicas: {{ .Values.api.replicas }}
  {{- end }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}api
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}api
        release: {{ .Release.Name }}
        version: {{ .Values.versionTag }}
    spec:
      initContainers:
        - name: wait-for-db
          image: busybox
          command: ['sh', '-c', 'until nc -z {{ .Release.Name }}-dbsvc {{ .Values.service.dbPort }}; do echo waiting for db; sleep 2; done;']
      containers:
        - name: api
          image: "{{ .Values.api.image.repository }}:{{ .Values.versionTag }}"
          ports:
          - name: http
            containerPort: {{ .Values.service.apiPort }}
            protocol: TCP
          env:
          - name: DATABASE_URL
            value: "mysql://root:{{ .Values.database.rootPassword }}@{{ .Release.Name }}-dbsvc:{{ .Values.service.dbPort }}/{{ .Values.database.databaseName }}"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
