versionTag: v0.5

api:
  image:
    repository: docker.io/danijels/cg-distr-api
  replicas: 1
  autoscaling:
    enabled: false
    minReplicas: 2
    maxReplicas: 6
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80

database:
  image:
    repository: mysql
    tag: "8.0"
  replicas: 1
  rootPassword: rootpassword
  databaseName: distributors
  initScriptConfigMap: init-cg

service:
  apiPort: 80
  containerPort: 8080
  dbPort: 3306

resources:
  limits:
    cpu: 100m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 256Mi
