versionTag: v0.1

api:
  image:
    repository: docker.io/danijels/cg-distr-api
  replicas: 1
  resources:
    limits:
      cpu: 500m
      memory: 1024Mi
    requests:
      cpu: 250m
      memory: 512Mi
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 6
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80
      
database:
  image:
    repository: mysql
    tag: "8.0"
  replicas: 1
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi
  rootPassword: password
  databaseName: distributors
  initScriptConfigMap: init-script

service:
  apiPort: 8080
  dbPort: 3306
