replicaCount: 1
versionTag: v0.3.16

image:
  repository: docker.io/danijels/cg-ui-api
  pullPolicy: Always
service:
  type: ClusterIP
  port: 80
ingress:
  enabled: true
  className: ""
  annotations: {}
  hosts:
  - host: chart-example.local
    paths:
    - path: /
      pathType: ImplementationSpecific
apiBaseUrl: http://20.251.73.226/api
appBaseUrl: /ui
