replicaCount: 1
versionTag: v0.3.16
apiBaseUrl: http://20.251.16.133/api
appBaseUrl: /ui

image:
  repository: docker.io/danijels/cg-ui-api
  pullPolicy: Always
service:
  type: ClusterIP
  port: 80
ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
  - host: chart-example.local
    paths:
    - path: /
      pathType: ImplementationSpecific

resources:
  limits:
    cpu: 100m
    memory: 1024Mi
  requests:
    cpu: 100m
    memory: 1024Mi
