apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-api
  labels:
    app: {{ .Release.Name }}api
    release: {{ .Release.Name }}
    version: {{ .Values.versionTag }}
spec:
  replicas: {{ .Values.api.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}api
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}api
        release: {{ .Release.Name }}
        version: {{ .Values.versionTag }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.api.image.repository }}:{{ .Values.versionTag }}"
          imagePullPolicy: {{ .Values.api.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.api.service.port }}
              protocol: TCP
          env:
            - name: DB_HOST
              value: "vatdb-svc"
            - name: PORT
              value: "{{ .Values.api.service.port }}"
            - name: DB_USER
              value: root
            - name: DB_PASSWORD
              value: {{ .Values.database.rootPassword }}
            - name: DB_NAME
              value: {{ .Values.database.databaseName }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
