apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-svc
  labels:
    app: {{ .Release.Name }}svc
    release: {{ .Release.Name }}
spec:
  type: {{ .Values.api.service.type }}
  ports:
    - port: {{ .Values.api.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ .Release.Name }}api
    release: {{ .Release.Name }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-dbsvc
  labels:
    app: {{ .Release.Name }}dbsvc
    release: {{ .Release.Name }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.database.dbPort }}
      targetPort: {{ .Values.database.dbPort }}
      protocol: TCP
      name: mysql
  selector:
    app: {{ .Release.Name }}db
    release: {{ .Release.Name }}
